name: CI/CD - Build and Deploy ASP.NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore AnonConfessionWall/AnonConfessionWall.csproj

    - name: Build project
      run: dotnet build AnonConfessionWall/AnonConfessionWall.csproj --configuration Release --no-restore

    - name: Run tests (optional)
      run: dotnet test AnonConfessionWall/AnonConfessionWall.csproj --no-build || echo "No tests found or failed"

    - name: Publish app
      run: dotnet publish AnonConfessionWall/AnonConfessionWall.csproj -c Release -o publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: publish

  deploy:
    name: Deploy to EC2
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Download published artifact
      uses: actions/download-artifact@v4
      with:
        name: published-app
        path: publish

    - name: Upload to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "publish/*"
        target: "/home/${{ secrets.EC2_USER }}/anonconfessionwall"

    - name: Restart ASP.NET Core app
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo systemctl restart aspnetapp
